# Generated by Django 5.2.7 on 2026-09-27 18:20

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion', models.TextField()),
                ('rev', models.PositiveIntegerField()),
                ('value', models.PositiveSmallIntegerField()),
                ('state', models.TextField()),
                ('comment', models.TextField()),
                ('audit_seq', models.BigIntegerField()),
            ],
            options={
                'db_table': 'score_current',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.TextField(blank=True, default='')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='AssignmentRun',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('kind', models.TextField()),
                ('seed', models.BigIntegerField(default=1)),
                ('params', models.JSONField(default=dict)),
                ('report', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'assignment_run',
            },
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('kind', models.TextField(default='bearer')),
                ('token_sha256', models.CharField(max_length=64, unique=True)),
                ('scopes', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('demo', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_token',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('state', models.TextField(default='draft')),
                ('submissions_close', models.DateTimeField()),
                ('windows', models.JSONField(blank=True, default=dict)),
                ('blind_judging', models.BooleanField(default=False)),
                ('custom_questions', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'event',
                'constraints': [models.CheckConstraint(condition=models.Q(('state__in', ('draft', 'open', 'closed', 'judging', 'published', 'archived'))), name='event_state')],
            },
        ),
        migrations.CreateModel(
            name='DuplicateGroup',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('rule', models.TextField()),
                ('members', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('resolution', models.TextField(default='keep_latest')),
                ('status', models.TextField(default='provisional')),
                ('resolved_by', models.TextField(blank=True, default='')),
                ('audit_seq', models.BigIntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicates', to='portal.event')),
            ],
            options={
                'db_table': 'duplicate_group',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('state', models.TextField(default='issued')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='portal.assignmentrun')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='portal.event')),
            ],
            options={
                'db_table': 'batch',
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('seq', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor', models.TextField()),
                ('action', models.TextField()),
                ('object_ref', models.TextField(db_column='object')),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('prev_hash', models.TextField()),
                ('hash', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='portal.event')),
            ],
            options={
                'db_table': 'audit_event',
                'ordering': ['seq'],
            },
        ),
        migrations.AddField(
            model_name='assignmentrun',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_runs', to='portal.event'),
        ),
        migrations.CreateModel(
            name='NormalizationRun',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('method', models.TextField()),
                ('params', models.JSONField(default=dict)),
                ('input_sha256', models.TextField(blank=True, default='')),
                ('output', models.JSONField(default=dict)),
                ('state', models.TextField(default='ok')),
                ('seconds', models.FloatField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalization_runs', to='portal.event')),
            ],
            options={
                'db_table': 'normalization_run',
            },
        ),
        migrations.CreateModel(
            name='ResultsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('method', models.TextField()),
                ('ranking_sha256', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(default=dict)),
                ('cause_audit_seq', models.BigIntegerField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('seconds', models.FloatField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='portal.event')),
            ],
            options={
                'db_table': 'results_snapshot',
            },
        ),
        migrations.CreateModel(
            name='RoleGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='portal.event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'role_grant',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('title', models.TextField(blank=True, default='')),
                ('tagline', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('thumbnail', models.TextField(blank=True, default='')),
                ('video_url', models.TextField(blank=True, default='')),
                ('repo_url', models.TextField(blank=True, default='')),
                ('live_url', models.TextField(blank=True, default='')),
                ('tech_tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('custom_answers', models.JSONField(blank=True, default=dict)),
                ('state', models.TextField(default='draft')),
                ('origin', models.TextField(default='native')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('withdrawn_reason', models.TextField(blank=True, default='')),
                ('duplicate_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='portal.duplicategroup')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='portal.event')),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='portal.submission')),
            ],
            options={
                'db_table': 'submission',
            },
        ),
        migrations.CreateModel(
            name='ScoreRev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion', models.TextField()),
                ('rev', models.PositiveIntegerField()),
                ('value', models.PositiveSmallIntegerField()),
                ('state', models.TextField()),
                ('comment', models.TextField(blank=True, default='')),
                ('audit_seq', models.BigIntegerField()),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_revs', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_revs', to='portal.submission')),
            ],
            options={
                'db_table': 'score_rev',
            },
        ),
        migrations.CreateModel(
            name='DeadlineException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('until', models.DateTimeField()),
                ('granted_by', models.TextField()),
                ('audit_seq', models.BigIntegerField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='portal.submission')),
            ],
            options={
                'db_table': 'deadline_exception',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(default='import')),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='portal.batch')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='portal.submission')),
            ],
            options={
                'db_table': 'assignment',
            },
        ),
        migrations.CreateModel(
            name='SubmissionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.TextField()),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('sha256', models.CharField(max_length=64)),
                ('content_type', models.TextField()),
                ('path', models.TextField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='portal.submission')),
            ],
            options={
                'db_table': 'submission_media',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='portal.event')),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='portal.team'),
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('token_sha256', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('uses', models.PositiveIntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='portal.team')),
            ],
            options={
                'db_table': 'invite',
            },
        ),
        migrations.CreateModel(
            name='Coi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, default='')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='portal.team')),
            ],
            options={
                'db_table': 'coi',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='portal.team')),
            ],
            options={
                'db_table': 'team_member',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='portal.event')),
            ],
            options={
                'db_table': 'track',
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='portal.track'),
        ),
        migrations.CreateModel(
            name='PrizeCategory',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='portal.event')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.track')),
            ],
            options={
                'db_table': 'prize_category',
            },
        ),
        migrations.CreateModel(
            name='JudgeTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_tracks', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.track')),
            ],
            options={
                'db_table': 'judge_track',
            },
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('weight', models.DecimalField(decimal_places=4, max_digits=8)),
                ('scale_min', models.PositiveSmallIntegerField(default=1)),
                ('scale_max', models.PositiveSmallIntegerField(default=5)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='portal.event')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.track')),
            ],
            options={
                'db_table': 'criterion',
            },
        ),
        migrations.AddConstraint(
            model_name='duplicategroup',
            constraint=models.CheckConstraint(condition=models.Q(('resolution__in', ('keep_latest', 'merge'))), name='dup_resolution'),
        ),
        migrations.AddConstraint(
            model_name='duplicategroup',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('provisional', 'confirmed'))), name='dup_status'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ('issued', 'in_progress', 'done', 'abandoned'))), name='batch_state'),
        ),
        migrations.AddConstraint(
            model_name='normalizationrun',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ('ok', 'failed'))), name='norm_state'),
        ),
        migrations.AddConstraint(
            model_name='resultssnapshot',
            constraint=models.UniqueConstraint(fields=('event', 'seq'), name='snapshot_seq'),
        ),
        migrations.AddConstraint(
            model_name='rolegrant',
            constraint=models.UniqueConstraint(fields=('person', 'event', 'role'), name='role_grant_uniq'),
        ),
        migrations.AddConstraint(
            model_name='rolegrant',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ('participant', 'judge', 'organizer'))), name='role_grant_role'),
        ),
        migrations.AddConstraint(
            model_name='scorerev',
            constraint=models.UniqueConstraint(fields=('judge', 'submission', 'criterion', 'rev'), name='score_rev_uniq'),
        ),
        migrations.AddConstraint(
            model_name='scorerev',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 1), ('value__lte', 5)), name='score_value_scale'),
        ),
        migrations.AddConstraint(
            model_name='scorerev',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ('draft', 'final', 'unlocked'))), name='score_state'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('judge', 'submission'), name='assignment_once'),
        ),
        migrations.AddConstraint(
            model_name='submissionmedia',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ('thumbnail', 'gallery'))), name='media_kind'),
        ),
        migrations.AddConstraint(
            model_name='submissionmedia',
            constraint=models.CheckConstraint(condition=models.Q(('position__lte', 6)), name='media_position_cap'),
        ),
        migrations.AddConstraint(
            model_name='invite',
            constraint=models.CheckConstraint(condition=models.Q(('uses__lte', models.F('max_uses'))), name='invite_uses_cap'),
        ),
        migrations.AddConstraint(
            model_name='coi',
            constraint=models.UniqueConstraint(fields=('judge', 'team'), name='coi_uniq'),
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('event', 'person'), name='one_team_per_event'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ('draft', 'submitted', 'locked', 'withdrawn'))), name='submission_state'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(condition=models.Q(('origin__in', ('native', 'import'))), name='submission_origin'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(condition=models.Q(('origin', 'native'), models.Q(('state', 'withdrawn'), _negated=True)), fields=('event', 'team'), name='submission_one_active_native'),
        ),
        migrations.AddConstraint(
            model_name='judgetrack',
            constraint=models.UniqueConstraint(fields=('person', 'track'), name='judge_track_uniq'),
        ),
        migrations.AddConstraint(
            model_name='criterion',
            constraint=models.UniqueConstraint(fields=('event', 'track', 'key'), name='criterion_key', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='criterion',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gt', 0)), name='criterion_weight_positive'),
        ),
    ]
