# Generated by Django 5.2.7 on 2026-09-29 06:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_role_invites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('voter_type', models.TextField(default='account')),
                ('voter_email', models.EmailField(blank=True, default='', max_length=254)),
                ('session_key', models.CharField(blank=True, default='', max_length=64)),
                ('sequence_number', models.PositiveIntegerField(default=1)),
                ('channel', models.TextField(default='public')),
                ('excluded', models.BooleanField(default=False)),
                ('exclusion_reason', models.TextField(blank=True, default='')),
                ('credits_spent', models.PositiveIntegerField(default=0)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='portal.event')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ballots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ballot',
            },
        ),
        migrations.CreateModel(
            name='BallotLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.PositiveIntegerField()),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='portal.ballot')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ballot_lines', to='portal.submission')),
            ],
            options={
                'db_table': 'ballot_line',
            },
        ),
        migrations.CreateModel(
            name='MailOutbox',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('token_sha256', models.CharField(max_length=64, unique=True)),
                ('magic_url', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_outbox', to='portal.event')),
            ],
            options={
                'db_table': 'mail_outbox',
            },
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('state', models.TextField(default='pending')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('audit_seq', models.BigIntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='portal.event')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='portal.submission')),
            ],
            options={
                'db_table': 'project_comment',
            },
        ),
        migrations.CreateModel(
            name='VotingConfig',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('credit_budget', models.PositiveIntegerField(default=25)),
                ('allow_accounts', models.BooleanField(default=True)),
                ('allow_open', models.BooleanField(default=False)),
                ('open_token', models.CharField(blank=True, default='', max_length=64)),
                ('allow_email', models.BooleanField(default=False)),
                ('state', models.TextField(default='draft')),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voting_config', to='portal.event')),
            ],
            options={
                'db_table': 'voting_config',
            },
        ),
        migrations.CreateModel(
            name='VotingTally',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.TextField(blank=True, default='')),
                ('audit_seq', models.BigIntegerField()),
                ('payload', models.JSONField(default=dict)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voting_tally', to='portal.event')),
            ],
            options={
                'db_table': 'voting_tally',
            },
        ),
        migrations.AddConstraint(
            model_name='ballot',
            constraint=models.CheckConstraint(condition=models.Q(('voter_type__in', ('account', 'open', 'email'))), name='ballot_voter_type'),
        ),
        migrations.AddConstraint(
            model_name='ballot',
            constraint=models.CheckConstraint(condition=models.Q(('channel__in', ('participants', 'public'))), name='ballot_channel'),
        ),
        migrations.AddConstraint(
            model_name='ballot',
            constraint=models.UniqueConstraint(condition=models.Q(('person__isnull', False)), fields=('event', 'person'), name='ballot_account_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ballot',
            constraint=models.UniqueConstraint(condition=models.Q(('session_key', ''), _negated=True), fields=('event', 'session_key'), name='ballot_session_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ballot',
            constraint=models.UniqueConstraint(condition=models.Q(('voter_email', ''), _negated=True), fields=('event', 'voter_email'), name='ballot_email_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ballotline',
            constraint=models.UniqueConstraint(fields=('ballot', 'submission'), name='ballot_line_uniq'),
        ),
        migrations.AddConstraint(
            model_name='ballotline',
            constraint=models.CheckConstraint(condition=models.Q(('credits__gt', 0)), name='ballot_line_credits_positive'),
        ),
        migrations.AddConstraint(
            model_name='projectcomment',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ('pending', 'approved', 'rejected'))), name='comment_state'),
        ),
        migrations.AddConstraint(
            model_name='votingconfig',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ('draft', 'open', 'closed', 'counted'))), name='voting_config_state'),
        ),
        migrations.AddConstraint(
            model_name='votingconfig',
            constraint=models.CheckConstraint(condition=models.Q(('credit_budget__gt', 0)), name='voting_config_budget_positive'),
        ),
        migrations.RunSQL(
            sql=r"""
CREATE OR REPLACE FUNCTION voting_closed_guard() RETURNS trigger AS $$
DECLARE
  is_closed boolean;
BEGIN
  SELECT EXISTS (
    SELECT 1 FROM voting_tally WHERE event_id = NEW.event_id
  ) OR EXISTS (
    SELECT 1 FROM voting_config WHERE event_id = NEW.event_id AND state IN ('closed', 'counted')
  ) INTO is_closed;
  IF is_closed THEN
    RAISE EXCEPTION 'voting is closed';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS ballot_closed_guard ON ballot;
CREATE TRIGGER ballot_closed_guard
BEFORE INSERT OR UPDATE ON ballot
FOR EACH ROW EXECUTE FUNCTION voting_closed_guard();

CREATE OR REPLACE FUNCTION ballot_line_closed_guard() RETURNS trigger AS $$
DECLARE
  b_event_id text;
  is_closed boolean;
BEGIN
  SELECT event_id INTO b_event_id FROM ballot WHERE id = NEW.ballot_id;
  SELECT EXISTS (
    SELECT 1 FROM voting_tally WHERE event_id = b_event_id
  ) OR EXISTS (
    SELECT 1 FROM voting_config WHERE event_id = b_event_id AND state IN ('closed', 'counted')
  ) INTO is_closed;
  IF is_closed THEN
    RAISE EXCEPTION 'voting is closed';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS ballot_line_closed_guard ON ballot_line;
CREATE TRIGGER ballot_line_closed_guard
BEFORE INSERT OR UPDATE ON ballot_line
FOR EACH ROW EXECUTE FUNCTION ballot_line_closed_guard();

CREATE OR REPLACE FUNCTION ballot_budget_guard() RETURNS trigger AS $$
DECLARE
  b_event_id text;
  b_spent integer;
  b_budget integer;
BEGIN
  SELECT event_id INTO b_event_id FROM ballot WHERE id = NEW.ballot_id;
  SELECT credit_budget INTO b_budget FROM voting_config WHERE event_id = b_event_id;
  IF b_budget IS NOT NULL THEN
    IF TG_OP = 'INSERT' THEN
      SELECT COALESCE(SUM(credits), 0) + NEW.credits
      INTO b_spent
      FROM ballot_line
      WHERE ballot_id = NEW.ballot_id;
    ELSE
      SELECT COALESCE(SUM(credits), 0) + NEW.credits - OLD.credits
      INTO b_spent
      FROM ballot_line
      WHERE ballot_id = NEW.ballot_id;
    END IF;
    IF b_spent > b_budget THEN
      RAISE EXCEPTION 'ballot exceeds credit budget of %', b_budget;
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS ballot_budget_guard ON ballot_line;
CREATE TRIGGER ballot_budget_guard
BEFORE INSERT OR UPDATE ON ballot_line
FOR EACH ROW EXECUTE FUNCTION ballot_budget_guard();

DROP TRIGGER IF EXISTS voting_tally_append_only ON voting_tally;
CREATE TRIGGER voting_tally_append_only
BEFORE UPDATE OR DELETE ON voting_tally
FOR EACH ROW EXECUTE FUNCTION append_only();
""",
            reverse_sql=r"""
DROP TRIGGER IF EXISTS voting_tally_append_only ON voting_tally;
DROP TRIGGER IF EXISTS ballot_budget_guard ON ballot_line;
DROP FUNCTION IF EXISTS ballot_budget_guard();
DROP TRIGGER IF EXISTS ballot_line_closed_guard ON ballot_line;
DROP FUNCTION IF EXISTS ballot_line_closed_guard();
DROP TRIGGER IF EXISTS ballot_closed_guard ON ballot;
DROP FUNCTION IF EXISTS voting_closed_guard();
""",
        ),
    ]
