# Generated by Django 5.2.7 on 2026-09-29 07:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_voting_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackRelease',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='feedback_release', serialize=False, to='portal.event')),
                ('released_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('audit_seq', models.BigIntegerField(blank=True, null=True)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback_release',
            },
        ),
        migrations.CreateModel(
            name='SignedRoot',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('publish_seq', models.PositiveIntegerField()),
                ('root_hash', models.CharField(max_length=64)),
                ('leaf_count', models.PositiveIntegerField()),
                ('signature_ed25519', models.TextField()),
                ('public_key_pem', models.TextField()),
                ('statement', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signed_roots', to='portal.event')),
            ],
            options={
                'db_table': 'signed_root',
                'ordering': ['-publish_seq'],
                'unique_together': {('event', 'publish_seq')},
            },
        ),
        migrations.CreateModel(
            name='JudgeProtocol',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(max_length=64, unique=True)),
                ('reviews_payload', models.JSONField(default=list)),
                ('statement_hash', models.CharField(max_length=64)),
                ('signature_ed25519', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_protocols', to='portal.event')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to=settings.AUTH_USER_MODEL)),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='portal.signedroot')),
            ],
            options={
                'db_table': 'judge_protocol',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('secret', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='portal.event')),
            ],
            options={
                'db_table': 'webhook_endpoint',
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=64)),
                ('msg_id', models.CharField(max_length=64)),
                ('timestamp', models.BigIntegerField()),
                ('payload', models.JSONField(default=dict)),
                ('signature', models.TextField()),
                ('status', models.CharField(default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_deliveries', to='portal.event')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='portal.webhookendpoint')),
            ],
            options={
                'db_table': 'webhook_delivery',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamCertificate',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(max_length=64, unique=True)),
                ('award_title', models.CharField(max_length=255)),
                ('is_winner', models.BooleanField(default=False)),
                ('payload_sha256', models.CharField(max_length=64)),
                ('signature_ed25519', models.TextField()),
                ('public_key_pem', models.TextField()),
                ('svg_content', models.TextField()),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_certificates', to='portal.event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='portal.team')),
            ],
            options={
                'db_table': 'team_certificate',
                'ordering': ['certificate_number'],
                'unique_together': {('event', 'team')},
            },
        ),
    ]
