import type {
  ProjectItem,
  ResultsPayload,
  VotingPayload,
  SignedRootPayload,
  ProgressPayload,
  JudgeBatchItem,
  AssignmentSheet,
} from './types';

export const FALLBACK_PROJECTS: ProjectItem[] = [
  {
    id: 'prj_01',
    title: 'Glass Signal',
    tagline: 'Cryptographic signal routing for distributed event meshes.',
    description: 'High-throughput mesh relay utilizing verifiable delay functions and zero-knowledge gossip propagation.',
    track: 'trk_04',
    track_name: 'Security',
    team_id: 'tm_01',
    team_name: 'NorthKiln',
    state: 'submitted',
    repo_url: 'https://github.com/northkiln/glass-signal',
    live_url: 'https://glass-signal.demo',
    n_reviews: 3,
    submitted_at: '2026-02-27T04:08:00Z',
    badge: 'Finalist',
  },
  {
    id: 'prj_34',
    title: 'Iron Switch',
    tagline: 'Low-latency stateful fault injection for distributed databases.',
    description: 'Automated chaos engineering daemon applying deterministic network partitioning at kernel level.',
    track: 'trk_08',
    track_name: 'Systems',
    team_id: 'tm_34',
    team_name: 'FerroCore',
    state: 'submitted',
    repo_url: 'https://github.com/ferrocore/iron-switch',
    live_url: 'https://iron-switch.systems',
    n_reviews: 3,
    submitted_at: '2026-02-28T12:00:00Z',
    badge: 'Track Winner',
  },
  {
    id: 'prj_11',
    title: 'Salt Ledger',
    tagline: 'Append-only ledger with streaming zero-knowledge balance assertions.',
    description: 'Ultra-compact cryptographic accounting records verified in sub-millisecond cycles.',
    track: 'trk_02',
    track_name: 'Data & Analytics',
    team_id: 'tm_11',
    team_name: 'Halite Labs',
    state: 'submitted',
    repo_url: 'https://github.com/halite/salt-ledger',
    live_url: 'https://saltledger.dev',
    n_reviews: 4,
    submitted_at: '2026-02-27T18:30:00Z',
  },
  {
    id: 'prj_15',
    title: 'Copper Orbit',
    tagline: 'Decentralized consensus protocol over constrained satellite links.',
    description: 'High-resilience delay-tolerant gossip network specifically optimized for intermittent orbital uplinks.',
    track: 'trk_04',
    track_name: 'Security',
    team_id: 'tm_15',
    team_name: 'AstroMesh',
    state: 'submitted',
    repo_url: 'https://github.com/astromesh/copper-orbit',
    live_url: 'https://copper-orbit.space',
    n_reviews: 3,
    submitted_at: '2026-02-26T21:14:00Z',
  },
  {
    id: 'prj_22',
    title: 'Dry Bridge',
    tagline: 'Cross-subnet atomic liquidity routing with fraud-proof guarantees.',
    description: 'Trust-minimized bridge layer implementing optimistic fraud windows and verifiable zero-copy messaging.',
    track: 'trk_04',
    track_name: 'Security',
    team_id: 'tm_22',
    team_name: 'Pontis Tech',
    state: 'submitted',
    repo_url: 'https://github.com/pontis/dry-bridge',
    live_url: 'https://drybridge.network',
    n_reviews: 3,
    submitted_at: '2026-02-27T09:45:00Z',
  },
  {
    id: 'prj_06',
    title: 'Dry Compass',
    tagline: 'Spatial coordinate consensus for off-grid rescue drones.',
    description: 'Peer-to-peer positioning mesh combining ultra-wideband time-of-flight ranging with Byzantine fault tolerance.',
    track: 'trk_01',
    track_name: 'Developer Tools',
    team_id: 'tm_06',
    team_name: 'Wayfinder Collective',
    state: 'submitted',
    repo_url: 'https://github.com/wayfinder/dry-compass',
    live_url: 'https://compass.mesh',
    n_reviews: 3,
    submitted_at: '2026-02-28T02:11:00Z',
  },
];

export const FALLBACK_RESULTS: ResultsPayload = {
  title: 'Evaluated Results · Sample Hack 2026',
  event: 'evt_01',
  method: 'reml',
  lambda: '1.240',
  ranking_sha256: '9a5c898c6731baefad69f21d3f9b84013149ba5845c432d8479e0a35987a0709',
  published: true,
  published_at: '2026-03-02T10:00:00Z',
  count: 40,
  items: [
    {
      id: 'prj_34',
      title: 'Iron Switch',
      rank: 1,
      rank_lo: 1,
      rank_hi: 3,
      adjusted: '4.334',
      raw_mean: '4.333',
      raptors_k10: '3.751',
      n_reviews: 3,
      p_top5: '0.684',
      tie_group: 1,
      track_rank: 1,
      track: 'trk_08',
      method: 'reml',
    },
    {
      id: 'prj_11',
      title: 'Salt Ledger',
      rank: 2,
      rank_lo: 1,
      rank_hi: 4,
      adjusted: '4.318',
      raw_mean: '4.333',
      raptors_k10: '3.792',
      n_reviews: 4,
      p_top5: '0.705',
      tie_group: 2,
      track_rank: 1,
      track: 'trk_02',
      method: 'reml',
    },
    {
      id: 'prj_01',
      title: 'Glass Signal',
      rank: 3,
      rank_lo: 2,
      rank_hi: 6,
      adjusted: '4.182',
      raw_mean: '4.200',
      raptors_k10: '3.620',
      n_reviews: 3,
      p_top5: '0.612',
      tie_group: 3,
      track_rank: 1,
      track: 'trk_04',
      method: 'reml',
    },
    {
      id: 'prj_15',
      title: 'Copper Orbit',
      rank: 4,
      rank_lo: 2,
      rank_hi: 7,
      adjusted: '4.120',
      raw_mean: '4.150',
      raptors_k10: '3.580',
      n_reviews: 3,
      p_top5: '0.540',
      tie_group: 4,
      track_rank: 2,
      track: 'trk_04',
      method: 'reml',
    },
    {
      id: 'prj_06',
      title: 'Dry Compass',
      rank: 5,
      rank_lo: 3,
      rank_hi: 9,
      adjusted: '4.045',
      raw_mean: '4.000',
      raptors_k10: '3.510',
      n_reviews: 3,
      p_top5: '0.480',
      tie_group: 5,
      track_rank: 1,
      track: 'trk_01',
      method: 'reml',
    },
  ],
};

export const FALLBACK_BATCHES: JudgeBatchItem[] = [
  {
    project_id: 'prj_15',
    title: 'Copper Orbit',
    track: 'trk_04',
    batch_id: 'bat_demo_jdg_08',
    batch_state: 'issued',
    finalized: false,
    status: 'to score',
  },
  {
    project_id: 'prj_22',
    title: 'Dry Bridge',
    track: 'trk_04',
    batch_id: 'bat_demo_jdg_08',
    batch_state: 'issued',
    finalized: false,
    status: 'to score',
  },
];

export const FALLBACK_ASSIGNMENT: AssignmentSheet = {
  title: 'Copper Orbit',
  event: 'evt_01',
  project_id: 'prj_15',
  tagline: 'Decentralized consensus protocol over constrained satellite links.',
  description: 'High-resilience delay-tolerant gossip network specifically optimized for intermittent orbital uplinks.',
  repo_url: 'https://github.com/astromesh/copper-orbit',
  live_url: 'https://copper-orbit.space',
  track: 'trk_04',
  criteria: [
    { key: 'functionality', label: 'Functionality & Correctness', weight: 1, value: 4 },
    { key: 'quality', label: 'Engineering Quality & Tests', weight: 1, value: 4 },
    { key: 'innovation', label: 'Novelty & Architecture', weight: 1, value: 5 },
  ],
  comment: 'Remarkable fault recovery mechanisms during connection drops. Thorough testing setup.',
  finalized: false,
};

export const FALLBACK_VOTING: VotingPayload = {
  title: 'Community Quadratic Voting · Sample Hack 2026',
  event: 'evt_01',
  state: 'open',
  credit_budget: 25,
  credits_spent: 0,
  voter: {
    type: 'participant',
    channel: 'participants',
    excluded: false,
  },
  items: [
    { project_id: 'prj_01', title: 'Glass Signal', tagline: 'Cryptographic signal routing for distributed event meshes.', credits: 0 },
    { project_id: 'prj_34', title: 'Iron Switch', tagline: 'Low-latency stateful fault injection for distributed databases.', credits: 0 },
    { project_id: 'prj_11', title: 'Salt Ledger', tagline: 'Append-only ledger with streaming zero-knowledge assertions.', credits: 0 },
    { project_id: 'prj_15', title: 'Copper Orbit', tagline: 'Decentralized consensus protocol over constrained satellite links.', credits: 0 },
    { project_id: 'prj_06', title: 'Dry Compass', tagline: 'Spatial coordinate consensus for off-grid rescue drones.', credits: 0 },
  ],
};

export const FALLBACK_SIGNED_ROOT: SignedRootPayload = {
  title: 'Signed Records Root · Sample Hack 2026',
  event: 'evt_01',
  root_hash: 'b97363e8d4e8d2f6e145469b2885aba79bdf4fbf8db89768b6f52597b874ae66',
  leaf_count: 378,
  publish_seq: 1,
  signature_ed25519: 'DAiDgjuzCC/sthuHnZ62u7Mzq8Vrm18wQHqd5FzurrFwkHY3HUkjbVTjVOYZIiBBlktZp1v2rXNP7DUnRVE0Aw==',
  public_key_pem: `-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAyb2SJQf7Sg6e6IRcs5V5iLE3ZsWMHlEVkR6tPgKWgZE=\n-----END PUBLIC KEY-----`,
  statement: `SAMEPAGE PUBLISHED ROOT\nEvent: evt_01\nPublish-Seq: 1\nLeaves: 378\nRoot-SHA256: b97363e8d4e8d2f6e145469b2885aba79bdf4fbf8db89768b6f52597b874ae66\nTimestamp: 2026-03-02T10:00:00Z`,
  verify_command: `openssl dgst -sha256 -verify pub.pem -signature root.sig root.txt`,
};

export const FALLBACK_PROGRESS: ProgressPayload = {
  title: 'Evaluation Progress & Normalization Readiness',
  event: 'evt_01',
  sentence: {
    counted: 121,
    excluded: 5,
    total: 126,
    fully_reviewed: 32,
    active: 40,
    short: 8,
    withdrawn_duplicate: 1,
  },
  metrics: [
    { key: 'counted', value: 121, label: 'Counted reviews in consensus matrix' },
    { key: 'excluded', value: 5, label: 'Excluded reviews (conflict / duplicate)' },
    { key: 'total', value: 126, label: 'Total submitted evaluations' },
    { key: 'fully_reviewed', value: 32, label: 'Projects meeting min-reviews quota' },
    { key: 'active', value: 40, label: 'Active accepted submissions' },
    { key: 'short', value: 8, label: 'Submissions pending 1 top-up review' },
  ],
};

export const FALLBACK_AUDIT: import('./types').AuditItem[] = [
  {
    seq: 142,
    timestamp: '2026-03-02T09:45:12Z',
    actor: 'organizer@samepage.live',
    role: 'organizer',
    action: 'results.publish',
    target: 'evt_01:ranking_sha:9a5c898c',
    prev_hash: '3f7c9e01...88ab',
    entry_hash: '9a5c898c6731baefad69f21d3f9b84013149ba5845c432d8479e0a35987a0709',
  },
  {
    seq: 141,
    timestamp: '2026-03-02T09:30:00Z',
    actor: 'organizer@samepage.live',
    role: 'organizer',
    action: 'reml.convergence_check',
    target: 'lambda=1.240, tol=1e-5, status=converged',
    prev_hash: '2e1b4c88...12fa',
    entry_hash: '3f7c9e01a88b56cd4091eef017c62b9a1190bcda45e2194688ab09121854bc3e',
  },
  {
    seq: 140,
    timestamp: '2026-03-02T08:15:22Z',
    actor: 'judge@samepage.live',
    role: 'judge',
    action: 'scores.finalize',
    target: 'prj_15 (Copper Orbit)',
    prev_hash: '11aa49bc...77cc',
    entry_hash: '2e1b4c88e99fa281bba29048f71295b9a4c09d57a911a3b112fa57390918ca12',
  },
  {
    seq: 139,
    timestamp: '2026-03-02T07:54:10Z',
    actor: 'priya.nair@example.org',
    role: 'judge',
    action: 'scores.finalize',
    target: 'prj_22 (Dry Bridge)',
    prev_hash: '09cc88a1...55bd',
    entry_hash: '11aa49bc6723ef51da249cbb1058914ba31940ef82c4015677cc281765439a11',
  },
  {
    seq: 138,
    timestamp: '2026-03-02T06:20:00Z',
    actor: 'system',
    role: 'system',
    action: 'batch.balance_audit',
    target: 'batch_count=12, graph_connected=true',
    prev_hash: '00112233...aabb',
    entry_hash: '09cc88a123bcdefa9812734091823741829374918273948155bd819273849102',
  },
];

